server:
  port:
    8090

#blog:
#  # https://api.naccl.top
#  api:
#    http://localhost:${server.port}
#  # https://admin.naccl.top
#  cms:
#    http://localhost:8080
#  # https://naccl.top
#  view:
#    http://localhost:8081

spring:
  application:
    name:
      gblog-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: password

  data:
    redis:
      host: localhost
      port: 6379
      password: password # 如果设置了密码，则填写密码
      database: 0 # Redis数据库索引（默认为0）
      jedis:
        pool:
          max-active: 8 # 连接池最大连接数（使用Jedis时）
          max-wait: -1ms # 连接池最大阻塞等待时间（使用Jedis时）
          max-idle: 8 # 连接池中的最大空闲连接（使用Jedis时）
          min-idle: 0 # 连接池中的最小空闲连接（使用Jedis时）
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数（使用Lettuce时）
          max-wait: -1ms # 连接池最大阻塞等待时间（使用Lettuce时）
          max-idle: 8 # 连接池中的最大空闲连接（使用Lettuce时）
          min-idle: 0 # 连接池中的最小空闲连接（使用Lettuce时）

  # 修改地址，解决swagger报错问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    basic:
      path: /swagger-ui.html
      enabled: true
    user:
      name: admin #账号
      password: 123456  #密码
mybatis:
  # mapper映射文件包扫描 (这里是对应 resources 的文件路径)
  mapper-locations: classpath:fun/wuziran/gblogapi/mapper/*.xml
  # 实体类别名包扫描
  type-aliases-package: fun.wuziran.gblogapi.entity
  # 下划线格式映射驼峰格式
  configuration:
    map-underscore-to-camel-case: true





